[package]
name = "querylogger"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
msql-srv = "0.5"
mysql_common = "0.5"
mysql = "12.0.4"
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "884e763ad7fe8bb49061c42131b377a387708e09" }
